### ISSUE TITLE
[Mood Board] Se coordonner avec les autres équipes pour communiquer nos besoins externes.

### ISSUE THREAD

**Issue by CPicheney** [pjgrizel/mba#6]

**Comment by LNHVB** [comment]
Lors d'une réunion regroupant les représentants de chaque équipe, les besoins de chaque module en interactions avec les autres modules ont été communiqué à l 'ensemble des équipes. Un fichier a été réalisé pour servir de support pour le suivi des  besoins et des interdépendances. lors de cet entretien le dialogue et la compréhension de chacun a été au coeur des échanges.
