### ISSUE TITLE
Planifier les cérémonies.

### ISSUE THREAD

**Issue by CPicheney** [pjgrizel/mba#7]
Planifier les cérémonies de notre projet SCRUM (pour 2 sprints)

**Comment by LNHVB** [comment]
- 29 mai - semaine de framing
- 30/1er grooming

- 6 juin au 19 juin — sprint 1
- 6 juin matin - sprint planning 1 (toutes les équipes)
- 6 juin aprés midi - sprint planning 2 (sprint individuel équipe)
- 19 juin matin review
- 19 juin aprés midi retrospective equipe
- 15 juin grooming

- 20 juin au 3 juillet - sprint 2
- 21 juin matin overall retrospective
- 23 juin grooming
- 3 juillet matin review
- 3 juillet apres midi retrospective equipe
